[package]
name = "blackwall-app"
version = "0.1.0"
authors = ["YoEight <yo.eight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blackwall-api = { path = "../api" }
gl = "0.14.0"
